# Generated by Django 3.2.6 on 2021-10-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintCapacity',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('velocity', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacity', to='person.person')),
                ('sprint', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacity', to='sprint.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='SprintCapacityPresenceItem',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField()),
                ('presence', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('sprint_capacity', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacity_presence', to='capacity.sprintcapacity')),
            ],
        ),
    ]
