# Generated by Django 3.2.6 on 2021-10-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintcapacity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sprintcapacitypresenceitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
