# Generated by Django 3.2.6 on 2021-09-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='sprintcapacity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sprintcapacitypresenceitem',
            name='sprint_id',
        ),
        migrations.AddField(
            model_name='sprintcapacitypresenceitem',
            name='sprint_capacity_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacity.sprintcapacity'),
        ),
        migrations.AlterField(
            model_name='sprintcapacity',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacity.person'),
        ),
        migrations.AddField(
            model_name='sprintcapacity',
            name='sprint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacity.sprint'),
        ),
    ]
