# Generated by Django 3.2.6 on 2021-09-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0002_auto_20210914_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintcapacity',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='sprintcapacity',
            name='sprint_id',
        ),
        migrations.RemoveField(
            model_name='sprintcapacitypresenceitem',
            name='sprint_capacity_id',
        ),
        migrations.AddField(
            model_name='sprintcapacity',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacity', to='capacity.person'),
        ),
        migrations.AddField(
            model_name='sprintcapacity',
            name='sprint',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacity', to='capacity.sprint'),
        ),
        migrations.AddField(
            model_name='sprintcapacitypresenceitem',
            name='sprint_capacity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacity_presence', to='capacity.sprintcapacity'),
        ),
    ]
