# Generated by Django 3.2.8 on 2021-10-26 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_alter_sprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sprint',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
